
void menu(void);
/** \brief FUNCION -- (MUESTRA EL MENU DE OPCIONES)
 * \param PIDE -- (AL USUARIO ELEGIR UNA OPCION PARA REALIZAR UNA OPERACION)
 * \return DEVULVE -- ( OPCION QUE INGRESO EL USUARIO)
 */

float sumar(float,float);
/** \brief FUNCION -- (REALIZA LA OPERACION SUMA)
 * \param PIDE -- (AL USUARIO EL INGRESO DE LOS VALORES DE LOS OPERANDOS)
 * \return DEVUELVE -- (SUMA DE LA OPERACION)
 */

float restar(float,float);
/** \brief FUNCION -- (REALIZA LA OPERACION RESTA)
 * \param PIDE -- (AL USUARIO EL INGRESO DE LOS VALORES DE LOS OPERANDOS)
 * \return DEVUELVE --( RESTA DE LA OPERACION)
 */

float multiplicar(float,float);
/** \brief FUNCION -- (REALIZA LA OPERACION MULTIPLICAR)
 * \param PIDE -- (AL USUARIO EL INGRESO DE LOS VALORES DE LOS OPERANDOS)
 * \return DEVUELVE -- (MULTIPLICACION DE LA OPERACION)
 */

float dividir(float,float);
/** \brief FUNCION -- (REALIZA LA OPERACION DIVIDIR)
 * \param PIDE -- (AL USUARIO EL INGRESO DE LOS VALORES DE LOS OPERANDOS)
 * \return DEVUELVE -- (DIVISION DE LA OPERACION)
 */

long factorizar(float);
/** \brief FUNCION -- ( REALIZA LA OPERACION FACTORIAL DEL PRIMER OPERANDO)
 * \param PIDE -- (AL USUARIO EL INGRESO DE LOS VALORES DE LOS OPERANDOS)
 * \return DEVUELVE -- (FACTORIZACION DEL PRIMER OPERANDO)
 */

long factorizar2(float);

/** \brief FUNCION -- (REALIZA LA OPERACION FACTORIAL DEL PRIMER OPERANDO)
 * \param PIDE --( AL USUARIO EL INGRESO DE LOS VALORES DE LOS OPERANDOS)
 * \return DEVUELVE -- (FACTORIZACION DEL SEGUNDO OPERANDO)
 */
